name: zeronet-js
version: 0.0.1-alpha15
summary: ZeroNet in JS
description: |
  ZeroNet in JavaScript

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  zeronet-js:
    aliases:
      - zeronetjs
    command: bin/zeronet
    plugs:
      - network
      - network-bind

parts:
  node:
    plugin: nodejs
    node-engine: 8.2.1
    source: .empty
    build-packages:
      - python
      - gcc
  source:
    plugin: nil
    after:
      - node
    source: .
    build: |
      node scripts/no-git-deps.js package-lock.json
      bash scripts/tarball.sh
    install: |
      mkdir -p /tmp/$$/.{npm,node_gyp}
      npm_config_cache="/tmp/$$/.npm" npm_config_devdir="/tmp/$$/.node-gyp" npm_config_prefix="$SNAPCRAFT_PART_INSTALL" bash scripts/global.sh
      rm -rf /tmp/$$
