name: zeronet-js
version: 0.0.1-alpha15
summary: ZeroNet in JS
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  zeronet-js:
    aliases:
      - zeronetjs
    command: bin/zeronet
    plugs:
      - network
      - network-bind

parts:
  node:
    plugin: nodejs
    node-engine: 8.2.1
    source: .empty
  source:
    plugin: nil
    after:
      - node
    source: .
    build: |
      bash scripts/tarball.sh
    install: |
      npm_config_prefix="$SNAPCRAFT_PART_INSTALL" bash scripts/global.sh
